name          'puppet-jboss'
version       '0.1.0'
source        'https://github.com/terrimonster/puppet-jboss.git'
author        'Terri Haber'
license       'Apache 2.0'
summary       'Installs and manages Jboss 6 on RHEL 5 or 6'
description   'Installs and manages Jboss 6 on RHEL 5 or 6'
project_page  'https://github.com/terrimonster/puppet-jboss'

dependency 'puppetlabs/stdlib'
